"""create links table

Revision ID: 75e330228ec2
Revises: 
Create Date: 2026-06-12 00:19:51.154154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e330228ec2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_code', sa.String(length=16), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    # Start the id sequence at 62**5 so generated codes have >= 6 characters
    op.execute("ALTER SEQUENCE links_id_seq RESTART WITH 916132832")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###